spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_spring
    driver-class-name: com.mysql.jdbc.Driver
    username: Airy
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
