spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_spring
    driver-class-name: com.mysql.jdbc.Driver
    username: Airy
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  redis:
#    database: 0
#    host: 127.0.0.1
#    password: 1234
#    port: 6379
#    pool:
#      max-active: 100
#      max-idle: 8
#      min-idle: 0
#      max-wait: 1000
